from util.getAPI import getApiKey

POST_DATABASE_URL = getApiKey("POST_DB_URL")

POST_ENCRYPT_KEY = getApiKey("POST_ENCRYPT_KEY")

NEO_DATABASE_URL = getApiKey("NEO_DATABASE_URL")
NEO_DATABASE_USER = getApiKey("NEO_DATABASE_USER")
NEO_DATABASE_PASSWORD = getApiKey("NEO_DATABASE_PASSWORD")

REDIS_URL=getApiKey("REDIS_URL")
REDIS_PORT=getApiKey("REDIS_PORT")

GOOGLE_CLIENT_ID=getApiKey("GOOGLE_CLIENT_ID")
GOOGLE_SECURE_PASS=getApiKey("GOOGLE_SEC_PASS")
GOOGLE_REDIRECT_URL=getApiKey("GOOGLE_REDIRECT_URL")

TAVILY_API_KEY=getApiKey("TAVILY_API_KEY")

OPENAI_API_KEY = getApiKey("OPENAI_API_KEY")
OPENAI_MODEL = getApiKey("OPENAI_MODEL")
OPENAI_EMBEDDING_MODEL = getApiKey("OPENAI_EMBEDDING_MODEL")
GEMINI_MODEL = getApiKey("GEMINI_MODEL")
GEMINI_API_KEY = getApiKey("GEMINI_API_KEY")

SESSION_TTL = 60 * 60 * 24  # 1 day

VERIFY_PASS_URLS = [
    "/auth/google/login",
    "/auth/google/url",
    "/api/callback/auth/google"
]

MINIO_S3 = getApiKey("MINIO_S3")
MINIO_USER = getApiKey("MINIO_USER")
MINIO_PASSWORD = getApiKey("MINIO_PASSWORD")